#!/bin/sh /etc/rc.common
# WESHAH Agent init script for OpenWrt

START=99
STOP=10
USE_PROCD=1

PROG=/usr/sbin/weshah-agent
CONF=/etc/weshah-agent.conf

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 30 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "firewall" "network"
}
