package com.weshah.core.models

/**
 * System alert generated by the Alert Engine.
 * Alerts are persisted to Room and shown in the UI.
 */
data class Alert(
    val id: String,
    val timestamp: Long,
    val severity: AlertSeverity,
    val type: AlertType,
    val title: String,
    val message: String,
    val deviceMac: String?,     // associated device, if applicable
    val portId: String?,        // associated port, if applicable
    val isRead: Boolean = false,
    val isResolved: Boolean = false
)

enum class AlertSeverity { INFO, WARNING, CRITICAL }

enum class AlertType {
    NEW_DEVICE,
    UNKNOWN_DEVICE,
    WAN_DOWN,
    WAN_UP,
    WAN_SPEED_DEGRADED,
    HIGH_CPU,
    HIGH_RAM,
    HIGH_TEMPERATURE,
    PACKET_LOSS,
    CRC_ERRORS,
    PORT_DOWN,
    PORT_UP,
    PORT_SPEED_CHANGE,
    UNKNOWN_DHCP_SERVER,
    CONFIGURATION_CHANGED,
    SPEED_POLICY_CHANGED,
    DEVICE_OFFLINE,
    HIGH_BANDWIDTH_CONSUMER,
    LINK_FLAP,
    DNS_SLOW
}
